[package]
name = "gl-core"
version = "0.1.0"
edition = "2024"

[features]
test-utils = []

[dependencies]
tokio.workspace = true
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
url.workspace = true
tracing.workspace = true
rusqlite.workspace = true
rand.workspace = true
r2d2.workspace = true
r2d2_sqlite.workspace = true

[dev-dependencies]
tempfile = "3"
